### ISSUE TITLE
How can I see context.response.content in the browser?

### ISSUE THREAD

**Issue by YuyaNishimaki** [behave/behave-django#71]
Hello, 
I'm facing a problem, hoping that someone will help me.

### I'm trying to do: 
I want to run an authentication test of Django application using selenium in behave and behave-django. Also, I want to check the flow of execution of selenium by accessing the vnc server (vnc://localhost:5900).

### My environment: 
macOS(v10.14.1), Docker(v18.06.1-ce), Django(v2.1.4), behave(v1.2.6), behave-django(v1.1.0), selenium(v3.141.0)

### The problem: 
The vnc server refuses the access to the localhost. But, I can access the other websites, for exmaple, https://www.google.com/. Why?

<img width="300" alt="2018-12-10 15 41 07" src="https://user-images.githubusercontent.com/39610500/49718005-23c4d500-fc9c-11e8-9344-4a3a42d8aa07.png">

Also, I can probably check the error at `context.response.content.split()`, but it is very hard to see.

<img width="450" alt="2018-12-10 15 40 18" src="https://user-images.githubusercontent.com/39610500/49721550-d0f01b00-fca5-11e8-99c1-9b420f0f58a1.png">

Here, I know that the status_code is 200, and pages to be accessed certainly exists.
```
ipdb> context.response
<TemplateResponse status_code=200, "text/html; charset=utf-8">
ipdb> Page.objects.all()=6
```

### Questions:
1. How can I access to localhost?
2. How can I make context.response.content more readable?

**Comment by jenisys** [comment]
I assume the vnc-server is running in the Docker container and selenium is running on your host/PC.
Check the Dockerfile if you have mapped the vnc-server port to your host.
A mapping for the Web-server port probably exists (port: 80 for http, 443 for https).

**Comment by YuyaNishimaki** [comment]
Thank you for answering. However, the problem has not yet been solved.
I'm currently trying to access the web on local as follows: `browser.get("myapp.dev")`, but the access is rejected.

Here, environment.py is:
```
class SeleniumTestCase(StaticLiveServerTestCase):
    fixtures = ["test.yaml"]

    @classmethod
    def setUpClass(cls):
        cls.host = "myapp.dev"
        cls.port = 50000
        cls.browser = webdriver.Remote(
            command_executor="http://selenium_hub:4444/wd/hub",
            desired_capabilities=DesiredCapabilities.CHROME,
        )
        cls.browser.implicitly_wait(3)
        super(SeleniumTestCase, cls).setUpClass()

    def tearDown(self):
        self.browser.quit()
```

This is probably important, I'm using nginx as reverse-proxy on docker.
When accessing myapp.dev using selenium, nginx logs are not displayed at all.
That is,  I think reverse_proxy is not working well, how can I fix the problem?
Help me!!!!!

docker-compose.yml
```
myapp: 
    build: ~~~~~
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ~~~~~
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - ~~~~~
    env_file:
      - ~~~~~
    user: ~~~~~

  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - 50000:50000
      - 443:443
    depends_on:
      - selenium-node-chrome
      - selenium_hub
      - myapp
    links:
      - selenium_hub:hub
    volumes:
      - ~~~~~

  selenium_hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  selenium-node-chrome:
    image: selenium/node-chrome-debug
    links:
      - selenium_hub:hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5900:5900"
    depends_on:
      - selenium_hub
```
